### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


In [1]:
#import sys
#!{sys.executable} -m pip install numpy


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [13]:
dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [14]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [4]:
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)

object
float64
float64


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#If you use import numpy , all sub-modules and functions in the numpy module can only be accesses in the numpy.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [15]:
print(car.shape)
print(mpg.shape)
print(cylinders.shape)
# 406 rows by 1 column

(406,)
(406,)
(406,)


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [20]:
np.multiply(mpg, 12)
np.divide(mpg, 3)
mpg ** 4
np.sqrt(mpg)

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [26]:
horsepower.sum() # 42033.0
horsepower.min() # 0.0
horsepower.max() # 230.0
np.median(horsepower) # 93.5



93.5

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [28]:
acceleration[0:5] # array([12. , 11.5, 11. , 12. , 10.5])

array([12. , 11.5, 11. , 12. , 10.5])

In [29]:
acceleration[::2]

array([12. , 11. , 10.5,  9. , 10. , 17.5, 11. , 11. ,  8. ,  9.5, 15. ,
       15.5, 14.5, 17.5, 17.5, 15. , 15. , 18.5, 15.5, 19. , 13. , 15.5,
       15.5, 11.5, 13. , 12. , 13.5, 15. , 14. , 19.5, 19. , 19. , 15.5,
       23.5, 16.5, 12. , 13. , 11. , 13.5, 13.5, 14. , 14. , 18. , 18. ,
       17. , 15. , 13. , 13. , 12.5, 12. , 14.5, 11. , 16.5, 16. , 16. ,
       14. , 13. , 15. , 19.5, 13.5, 14. , 13. , 19.5, 14. , 11. , 13.5,
       16.5, 16. , 19. , 21. , 17. , 16.5, 14.5, 16. , 16.5, 14.5, 19. ,
       15.5, 15. , 16. , 16. , 19.5, 14. , 13.5, 18.5, 19. , 13.5, 16. ,
       16. , 13.5, 17. , 14. , 15. , 14.5, 17.5, 16.9, 17.7, 13. , 13.9,
       15.4, 17.6, 22.2, 14.2, 17.7, 16.2, 12.2, 16.4, 15.7, 21.9, 16.7,
       12. , 14. , 14.8, 15.5, 12.5, 13.7, 16.4, 17.7, 11.1, 12.2, 14.5,
       18.2, 17. , 16.4, 14.5, 13.5, 14.4, 18.6, 15.5, 12.8, 18.2, 15.4,
       17.2, 16.7, 15.1, 13.4, 13.7, 14.2, 14.5, 16.7, 14.9, 13.6, 15.8,
       16.6, 18.2, 18.2, 15.4, 13.2, 14.9, 15. , 14

8. Show how to select the number `99` in the array below. 

In [32]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])
select_99[1,2]                     

99

9. Select the last element in each subarray (do this with one operation.)

In [7]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])


In [33]:
select_more[: ,2]

array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [35]:
np.lookfor('log')
np.log(mpg)

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [36]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [54]:
np_2d = np.array([[car], [horsepower]])
print(np_2d.shape)
print(np_2d.ndim)
np_2d


(2, 1, 406)
3


array([[['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
         'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
         'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
         'Pontiac Catalina', 'AMC Ambassador DPL',
         'Citroen DS-21 Pallas', 'Chevrolet Chevelle Concours (sw)',
         'Ford Torino (sw)', 'Plymouth Satellite (sw)',
         'AMC Rebel SST (sw)', 'Dodge Challenger SE',
         "Plymouth 'Cuda 340", 'Ford Mustang Boss 302',
         'Chevrolet Monte Carlo', 'Buick Estate Wagon (sw)',
         'Toyota Corolla Mark ii', 'Plymouth Duster', 'AMC Hornet',
         'Ford Maverick', 'Datsun PL510',
         'Volkswagen 1131 Deluxe Sedan', 'Peugeot 504', 'Audi 100 LS',
         'Saab 99e', 'BMW 2002', 'AMC Gremlin', 'Ford F250',
         'Chevy C20', 'Dodge D200', 'Hi 1200D', 'Datsun PL510',
         'Chevrolet Vega 2300', 'Toyota Corolla', 'Ford Pinto',
         'Volkswagen Super Beetle 117', 'AMC Gremlin',
         'Plymouth Satellite Custom'

In [52]:
np_3d = np.array([[car],[horsepower], [origin]])
print(np_3d.shape)
print(np_3d.ndim)
np_3d

(3, 1, 406)
3


array([[['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
         'Plymouth Satellite', ..., 'Dodge Rampage', 'Ford Ranger',
         'Chevy S-10']],

       [[130.0, 165.0, 150.0, ..., 84.0, 79.0, 82.0]],

       [['US', 'US', 'US', ..., 'US', 'US', 'US']]], dtype=object)

In [53]:
np_4d = np.array([[car ], [horsepower] , [origin] , [mpg]])
print(np_4d.shape)
print(np_4d.ndim)
np_4d

(4, 1, 406)
3


array([[['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
         'Plymouth Satellite', ..., 'Dodge Rampage', 'Ford Ranger',
         'Chevy S-10']],

       [[130.0, 165.0, 150.0, ..., 84.0, 79.0, 82.0]],

       [['US', 'US', 'US', ..., 'US', 'US', 'US']],

       [[18.0, 15.0, 18.0, ..., 32.0, 28.0, 31.0]]], dtype=object)

13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [56]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [57]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [59]:
#The identity array is a square array with ones on the main diagonal.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [61]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
transpose_me.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

3. Why does this multiplication operation fail? 

In [62]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
# You can't multiply arrays that don't have the same amount of dimensions

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [65]:
average_horsepower = horsepower[ origin == 'Europe']
average_horsepower.mean()

78.78082191780823

5. On average are Japanse cars more fuel efficient than US cars? 

In [69]:
japan_cars = mpg[origin == 'Japan']
japan_cars.mean() # Japan average mpg is 30.45

usa_cars = mpg[origin == 'US']
usa_cars.mean() #USA average mpg is 19.86 

#cars from Japan has an higher average mpg then the US

19.688188976377955

6. What is the correlation coefficient of `mpg` and `weight`?

In [ ]:
# not sure researching this via Google. 

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
# If you want to store a large amount of data, then you should consider arrays because they can store data very compactly and efficiently.